source 'https://github.com/CocoaPods/Specs/git'
platform :ios, '10.0'
use_frameworks!

target 'RainyDayDonation' do
pod 'SnapKit', '>= 3.0.0'
pod 'TwicketSegmentedControl', '~> 0.1'
pod 'Mapbox-iOS-SDK', '~> 3.3'

end
